### PR TITLE
Refactor graphs package

### LINKED ISSUE #23: Refactor graphs package
`graphs` package needs to be refactored for maintainability and readability.

### PR DESCRIPTION
**Pull request by volmedo**
Closes #23 

All the logic to create the graph is currently living in a single function. Let's break it into smaller, easier to understand functions and make other improvements along the way.

### CODE REVIEW

**Comment by volmedo** [comment]
@ericm the PR is now ready for review. There are probably some other improvements that could be done, but I think the current changes already make a significant difference in terms of readability and maintainability.

PTAL and let me know what you think.

**Comment by ericm** [comment]
Could you fix the macos build? https://github.com/ericm/stonks/actions/runs/3257662825/jobs/5349081348

**Comment by volmedo** [comment]
I already did! 🙂 We need to merge [this other PR](https://github.com/ericm/stonks/pull/27) first. I decided to get it sorted in a different PR since it wasn't directly related with the refactor.

**Comment by ericm** [comment]
That or should be approved now. Rebase on top of master 😀

**Review by ericm — APPROVED** [review]

**Pull request merged**
